---
title: "Pikbasa"
author: "Vaishnav Sudarshan"
date: "2026-9-16"
categories:  [Conlangs]
abstract: A language where a picture is quite literally a thousand words. 
---

# Introduction

A picture is worth a thousand words, as you might have heard. But what if a picture is QUITE LITERALLY a thousand words??? 

# Basic setup

We have a matrix of pixels with 40 rows and 25 columns. Each pixel has a certain color and represents a unit of meaning (a thousand words would mean each pixel is a word, or Pikbasa is an isolating language; however, if you analyze each pixel as a morpheme, then we have a polysynthetic language where a picture is forty words - so let's not do that). 

# Color "Phonemes"

A pixel's color can be represented with its RGB values. Each component, from $0$ to $255$, has four intervals - $0: [0, 63]$, $1: [64, 127]$, $2: [128, 191]$, and $3: [192, 255]$. Three components makes $4^3=64$ possible colors, which I guess are the phonemes. Any two colors where each component is in the same interval will not be distinguished, and will be considered the same phoneme - for example, $(R,G,B) = (0,0,0)$ is the same phoneme as $(R,G,B) = (32,32,32)$. 

We can refer to a phoneme with its interval for each color component. For example, $/023/$ means the red is between $0$ and $63$, the green is between $128$ and $191$, and the blue is between $192$ and $255$. The order of the phonemes is the same order within the list of the same name here: 

```{python}
phonemes = []
for R in range(4):
    for G in range(4):
        for B in range(4):
            color = (R, G, B)
            phonemes.append(color)
```

# Within a row

Each row of $25$ pixels encodes a sentence. There are five chunks of five pixels. The first five indicate the subject, the next five the object, the next five the locative, the next five the ablative, and the final five the verb. Each of these has the same format.

$[\text{Color}][\text{Size}][\text{Goodness}][\text{Root}][\text{Syntactic Role}]$.

Let me clarify these first three a little.

Color is, well, the literal color, for nouns (including abstract stuff, because Pikbasians are just better like that). The color is encoded by a pixel of the same color. For verbs, it means something totally different - the *speed* at which the action was done. Slower means earlier phonemes, while faster means later phonemes. 

Size can mean the literal physical volume or mass or however you want to define "size" of an object. For verbs, it means how much (or hard) an action was done. Lower size means earlier phonemes, while higher size means later phonemes.

Goodness for both nouns and verbs is how good or bad the speaker views that noun or verb to be. And you guessed it! Worse means earlier phonemes, while better means later phonemes. 

Note that these adjectives/adverbs (except for color of a noun) are based on a scale from $0$ to $63$, according to the indices of the list of phonemes. 

There are $64$ semantic roots for nouns and verbs. I will put a dictionary at the end for that. 

Syntactic role is just the last pixel of the chunk, telling you whether it's the subject, object, locative, ablative, or verb. 

Since there is case marking, the word order is free. Any permutation of these five chunks is acceptable and equally grammatical. However, the order of words within a chunk is fixed. 

# Split Ergativity



# Multiple sentences

# Root dictionary