---
title: "My Experience With SLIYS"
author: "Vaishnav Sudarshan"
date: "2026-7-10"
categories:  [Miscellaneous Stuff]
abstract: I talk about a very unique opportunity that high schoolers interested in linguistics can take part in.
---

# Linguistics in High School

If you're in high school and you are interested in linguistics, chances are that your opportunities are pretty limited. The major thing you can do is take the North American Computational Linguistics Open (NACLO). However, the entire contest is built around the fact that most high schoolers don't have background linguistics knowledge, which is why the problems are based on logic and puzzle solving rather than linguistic theory. 

While I find language puzzles to be very fun, and they do sometimes teach you certain concepts in linguistics, they still don't replace actually learning linguistics. It's kind of like the difference between sudoku and algebra. 

During 8th and 9th grade, I was forced to learn linguistics through a combination of YouTube, Wikipedia, and ChatGPT - not exactly the best way to learn, although it was still much better than one might expect. 

# SLIYS

That's why I was thrilled to learn that every summer, the Ohio State University hosts a program called SLIYS (Summer Linguistics Institute for Youth Scholars) that actually formally teaches you the basics of linguistics. They have two one-week online sessions - SLIYS 1 and SLIYS 2, which are more introductory and more in-depth respectively. You have to take SLIYS 1 in order to be eligible to take SLIYS 2 later on. Sadly, I was only able to take SLIYS 1 this summer, because I had a schedule conflict during SLIYS 2, but I hope to take it next year. 

## Content 

I went into the program thinking I wouldn't learn that much, since I already knew a lot of linguistics beforehand. However, I was surprised that even for topics that I was sure I knew pretty well, I still ended up learning some new and interesting facts.

* Phonetics: This is split into first consonants, then vowels. For both, you learn the main features that are relevant in languages - voicing, place of articulation, and manner of articulation for consonants, and rounding, high/low, and front/back for vowels. However, I didn't know that there is also an independent distinction (can't be written in terms of the other three) for tense and lax vowels. 

* Sociolinguistics: You learn all about language variation, which is very interesting. It also clears up a lot of misconceptions that people who don't know about linguistics have, such as "I speak proper English, and everyone else speaks a dialect". One of the home labs (basically optional homework) was to watch a documentary called "Talking Black in America", which was very interesting.

* Morphology: You learn about the difficulty in defining makes a morpheme (is raspberry a single morpheme, or is "rasp" somehow a morpheme?) as well as different types of morphology across languages (using a decision tree to determine what type of morphology a language has is pretty cool).

* Syntax: You write rules for what sentences are valid, and you also make syntax trees. 

* Historical Linguistics: You learn about language change, including sound changes, but also morphology changes, which I didn't know before. 

## Elicitation

Apart from the lectures at SLIYS, one of the most fun parts is the language eliciation sessions. Basically, you get put into a language group with some other students, most likely a language you know almost nothing about. At the end of each day, you get to ask a native speaker of that language how to translate whatever phrases you want, and then you transcribe it into the IPA, with the goal of collecting and explaining data about the language. However, you can't ask about grammatical features directly - you can only ask for translations and figure it out yourself. Luckily, it's really easy to ask for minimal pair sentences to see what's going on.

I got placed in Thai. Transcribing it was very hard at first, because my puny English and Tamil speaking brain couldn't handle the tones and weird vowels I'd never heard before. However, once we figured that out, the morphology and syntax were super easy, and pretty cool as well. At the end of it, I was able to speak basic sentences in Thai (technically, infinite sentences because we figured out recursion, which works the same way as it does in English). 

## Panel Discussion

On the last day, we were able to ask questions to PhD and research students working in linguistics academia, and it was very cool to see what linguists actually do these days.

# Conclusion

Overall, SLIYS is an extremely unique opportunity that you get in high school to learn and do linguistics, and I'd strongly recommend that you participate in it if you want to learn more about the field.