project:
  type: website
  output-dir: ../docs

website:
  title: "Vaishnav Sudarshan's Blog on Cool Stuff"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vaishnavsudarshan
  comments: 
    giscus: 
      repo: vaishnavsudarshan/vaishnavsudarshan.github.io 
      repo-id: R_kgDONzCjJQ 
      category: Announcements 
      category-id: DIC_kwDONzCjJc4C_jEt 
      mapping: pathname 
      reactions-enabled: true 
      input-position: bottom 
      theme: light 
      language: en
        
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <script defer src="https://umami-production-36aa.up.railway.app/script.js" data-website-id="6558c60e-1ff1-49ad-bd30-bbf782d457c7"></script>


language:
  title-block-published: "Originally Published"
  title-block-modified: "Last Updated"



